AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Este stack va a crear
  una instancia y todo lo
  que necesita

Parameters:
  VpcIdParameter:
    Type: String
  KeyPairParameter:
    Type: String
  AmiIdParameter:
    Type: String
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t3.micro
      - t3.small    
      - t2.micro
    Description: El tipo de instancia a crear

Outputs:
  PublicIp:
    Description: IP Publica de la instancia
    Value: !GetAtt WebServer.PublicIp

  IdInstancia:
    Description: Id De la instancia que hemos creado
    Value: !Ref WebServer   
  foo1:
    Description: foo
    Value: !Base64 hola mundo esto es una prueba

Resources:
  WebServer:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: 
        Ref: AmiIdParameter
      KeyName: 
        Ref: KeyPairParameter
      InstanceType: 
        Ref: InstanceTypeParameter
      SecurityGroupIds: 
        - Ref: SecurityGroupSSH

  SecurityGroupSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group que permite acceso ssh"
      VpcId: 
        Ref: VpcIdParameter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0         
  